# Random Examples

In [3]:
import random

In [4]:
# random float in range of 0 to 1
a = random.random()
print(a)

0.7470179351566482


In [5]:
# random float within a specific range
random.uniform(1,10)

6.04118688445151

In [7]:
# random integer within a specific range
# upper bound included
random.randint(1,10)

8

In [8]:
# random integer within a specific range
# upper bound NOT included
random.randrange(1,10)

5

In [9]:
a = random.normalvariate(0, 1)
print(a)

-2.0344684675692233


## Random module to work with Sequences

In [30]:
mylist = list('ABCDEFGH')

# one element of list
a = random.choice(mylist)
print(a)

# 3 elements of list & all unique
a = random.sample(mylist, 3)
print(a)

# e elements of list & allow duplicates
a = random.choices(mylist, k=3)
print(a)

# shuffle the list elements in place
mylist = list("ABCDEFGHIJ")
random.shuffle(mylist)
print(mylist)

F
['A', 'H', 'G']
['D', 'F', 'H']
['E', 'J', 'H', 'C', 'D', 'G', 'A', 'F', 'B', 'I']


In [32]:
# Reproduce random data using seed() method
import random

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

random.seed(1)
print(random.random())
print(random.randint(1,10))

random.seed(2)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1
0.13436424411240122
2
0.9560342718892494
1


## Use `secrets` Module to generate Random data

In [2]:
# Generate random numbers which are not reproducable
import secrets

mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

a = secrets.randbits(4)
# 1111 -> 0-15
print(a)

F
10


## `numpy` Random Generator

In [6]:
import numpy as np

a = np.random.rand(3)
print(a)

print('--'*5)

a = np.random.rand(3,3)
print(a)

print('--'*5)

a = np.random.randint(0, 10, (3,4))
print(a)

[0.63166464 0.77748001 0.81086101]
----------
[[0.52932985 0.05370197 0.46949242]
 [0.90838483 0.69007654 0.24492129]
 [0.17432943 0.55089748 0.87932243]]
----------
[[0 8 2 6]
 [7 1 7 9]
 [4 1 9 1]]


#### Reproduciable random numbers

In [9]:
import numpy as np

np.random.seed(1)
print(np.random.rand(3))

np.random.seed(1)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]
